image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build_mps:
  stage: build
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -S . -B build
    - cd build && make mps
  artifacts:
    paths:
      - build/mps

unit_test:
  stage: test
  before_script:
    - apt update && apt -y install cmake gcovr
  script:
    - cmake -S . -B build
    - cd build
    - make mps_test
    - ctest
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml

make_input_dambreak:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cd input
    - cmake -S . -B build
    - cd build && make && cd ../
    - ./build/make_input
  artifacts:
    paths:
      - input/input.prof

dambreak:
  stage: test
  needs:
    - build_mps
    - make_input_dambreak
  script:
    - mkdir -p result/prof
    - mkdir -p result/vtu
    - ./build/mps
  artifacts:
    paths:
      - result/prof/*.prof
      - result/vtu/*.vtu