image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - run

build_gcc:
  stage: build
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - mkdir build
    - cd build
    - cmake -G "Ninja" ..
    - ninja
  artifacts:
    paths:
      - ./build/mps
      - ./build/mps_test

ctest:
  stage: test
  before_script:
    - apt update && apt -y install gcovr
  script:
    - cd build
    - ./mps_test
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml

dambreak:
  stage: run
  script:
    - mkdir result
    - mkdir result/prof
    - mkdir result/vtu
    - ./build/mps
  artifacts:
    paths:
      - result/prof/*.prof
      - result/vtu/*.vtu