image: gcc:11 # gcov is not available in gcc 12 yet

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build_mps:
  stage: build
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -S . -B build
    - cd build && make mps
  artifacts:
    paths:
      - build/mps

make_input_dambreak:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cd input
    - cmake -S . -B build
    - cd build && make && cd ../
    - ./build/make_input
  artifacts:
    paths:
      - input/input.prof

dambreak:
  stage: test
  needs:
    - build_mps
    - make_input_dambreak
  script:
    - mkdir -p result/prof
    - mkdir -p result/vtu
    - ./build/mps
  artifacts:
    paths:
      - result/prof/*.prof
      - result/vtu/*.vtu

doxygen:
  image: alpine
  stage: build
  before_script:
    - apk update && apk add doxygen ttf-freefont graphviz
  script: 
    - mkdir doxygen
    - doxygen Doxyfile
  artifacts:
    paths:
      - doxygen/latex

doxygen_latex:
  image: texlive/texlive
  stage: build
  needs:
    - doxygen
  script: 
    - cd doxygen/latex
    - make 
  artifacts:
    paths:
      - doxygen/latex/refman.pdf