image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build_mps:
  stage: build
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -G Ninja -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build/mps
      - build/generator/generate_dambreak

make_input_dambreak:
  needs:
    - build_mps
  script:
    - ./build/generator/generate_dambreak
  artifacts:
    paths:
      - input/dambreak/input.prof
      - input/dambreak/input.vtu

dambreak:
  stage: test
  needs:
    - build_mps
    - make_input_dambreak
  script:
    - ./scripts/linux.sh
  artifacts:
    paths:
      - result/dambreak/*.prof
      - result/dambreak/*.vtu

doxygen:
  image: alpine
  stage: build
  before_script:
    - apk update && apk add doxygen ttf-freefont graphviz
  script:
    - mkdir doxygen
    - doxygen Doxyfile
  artifacts:
    paths:
      - doxygen/latex

doxygen_latex:
  image: texlive/texlive
  stage: build
  needs:
    - doxygen
  script:
    - cd doxygen/latex
    - make
  artifacts:
    paths:
      - doxygen/latex/refman.pdf
