image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - mkdir build
    - cd build
    - cmake -G "Ninja" ..
    - ninja
  artifacts:
    paths:
      - ./build/mps
      - ./build/mps_test

test:
  stage: test
  script:
    - ./build/mps_test
